name: Build & Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      arch:
        description: "Arquitectura para compilar (amd64 o multi)"
        required: true
        default: "amd64"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set target platforms
        id: set-platform
        run: |
          if [ "${{ github.event.inputs.arch }}" = "multi" ]; then
            echo "PLATFORMS=linux/amd64,linux/arm64" >> $GITHUB_ENV
          else
            echo "PLATFORMS=linux/amd64" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: julianzanetti/portfolio:latest
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=registry,ref=julianzanetti/portfolio:cache
          cache-to: type=registry,ref=julianzanetti/portfolio:cache,mode=max
