name: Build and Push Docker Image

on:
  push:
    branches:
      - main

concurrency:
  group: 'docker-build-portfolio'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: julianzanetti/portfolio:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=julianzanetti/portfolio:cache
          cache-to: type=registry,ref=julianzanetti/portfolio:cache,mode=max

